### ISSUE TITLE
Needs-release GH label failed to trigger release

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-akamai#528]
### What happened?

https://github.com/pulumi/pulumi-akamai/pull/524 - this failed to trigger a release after merging

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
The original run of the master build shows a status of Cancelled. This means that the "Tag Release id labeled as needs-release" job never ran.

Apparently it also means that we did not get a p1 alert because Cancelled does not mean Failed.

<img width="667" alt="Screenshot 2024-06-03 at 12 39 15 PM" src="https://github.com/pulumi/pulumi-akamai/assets/13116240/f78d42ca-b1ba-44a6-86cd-b0304847e8d5">

I believe this is a recent GitHub Actions issue and has been resolved since. The timeline adds up.
https://github.com/orgs/community/discussions/126539

**Comment by guineveresaenger** [comment]
Thank you to @VenelinMartinov for manually releasing the affected providers.

Also of note: Cleaning up the `needs-release/x` label did not work on the manually triggered release because it was looking for a commit not on that branch.

I've cleaned up the labels on both repositories. I've also verified that there are no other `needs-release/x` labels assigned to me as reviewer recently, so I have high confidence that this was fixed by GitHub.

I'm going to close this issue as resolved but have opened https://github.com/pulumi/home/issues/3456 to track if it happens again. I don't believe this is high priority at this time.
